runtime: nodejs
runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "20"
handlers:
  - url: /.*
    script: auto
env: flex
network:
  session_affinity: true

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5